server:
  port: 9090
  context-path: /sdhighway
spring:
    http.multipart.maxFileSize: 10MB
    datasource:
        name: test
        url: jdbc:mysql://39.106.121.250:3306/sdwl?charset=utf8
        username: manto
        password: j7DRsua&5xrH
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
    redis:
      host: 192.168.2.248
      port: 6379
      password: admin
mybatis:
    type-aliases-package: com.highway.model
    mapper-locations: classpath:mapper/*.xml
mapper:
    mappers: com.highway.mapper.CommonMapper
    not-empty: false
    identity: MYSQL
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
image:
    filePath: /data/www/highway/upload/
    fileHeader: FFD8FF,89504E47,47494638,49492A00,424D,504B0304,D0CF11E0,D0CF11E0,00000000
    fileType: .jpg,.gif,.png,.bmp,.jpeg,.zip,.xlsx,.doc,.xls,.docx,.txt,.pdf
    url: 39.108.5.62:8080
logging:
  file: D:/log/test.log
  level: DEBUG